// <auto-generated />
namespace EverythingListApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class appmigrationv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appmigrationv1));
        
        string IMigrationMetadata.Id
        {
            get { return "201809181602528_app-migration-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
